language: java
jdk: oraclejdk11

os: linux

dist: trusty

addons:
  chrome: stable

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - # start your web application and listen on `localhost`
  - 'google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &'
  - wget https://services.gradle.org/distributions/gradle-5.6.2-bin.zip
  - unzip -qq gradle-5.6.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.2
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

jobs:
  include:
    # Build/Assembly stage
    - stage: Assembly
      install: skip
      before_script: echo "<STAGE 'Assembly 'is launching up...>"
      script: gradle assemble
      after_success: echo "<STAGE 'Assembly 'has been executed successfully>"
      after_failure: echo "<STAGE 'Assembly 'has been failed>"

    # Test stage
    - stage: Test
      name: "[allure.integration] Module Tests"
      script:
        - cd allure.integration
        - gradle test

    - stage: Test
      name: "[allure.testng.bridge] Module Tests"
      script:
        - cd allure.testng.bridge
        - gradle test

    - stage: Test
      name: "[check] Module Tests"
      script:
        - cd check
        - gradle test

    - stage: Test
      name: "[core.api] Module Tests"
      script:
        - cd core.api
        - gradle test

    - stage: Test
      name: "[data.base.api] Module Tests"
      script:
        - cd data.base.api
        - gradle test

    - stage: Test
      name: "[http.api] Module Tests"
      script:
        - cd http.api
        - gradle test

    - stage: Test
      name: "[selenium] Module Tests"
      script:
        - cd selenium
        - gradle test

    - stage: Test
      name: "[testng.integration] Module Tests"
      script:
        - cd testng.integration
        - gradle test

    # in case of a need for continuous deployment (Docker as an example), you have to set up this stage
    # Follow-up step is to make 'Heroku' account to do so
    # Deployment stage
    - stage: Deploy
      install: skip
      script: skip
      provider: skip
